services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345678}
      POSTGRES_DB: ${DB_DATABASE:-app}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
